#! /usr/bin/env bash

set -e

# file to ran as an arg
FILE=$1
INJECT=lib/inject.py

# shift arguments
shift

# inject the inject.py to file
SRC=$(cat ${INJECT} ${FILE})

IMPORTS=$(echo "${SRC}" | grep '^import\s')
REST=$(echo "${SRC}" | grep -v '^import\s')

NEW_MODULE=$IMPORTS$REST

# Eval using python
echo "${NEW_MODULE}" | python3 $@
